[package]
name = "bin"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "homelink"
path = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib = { path = "../lib" }
hap_metadata = { path = "../hap_metadata" }
axum.workspace = true
log4rs.workspace = true
log.workspace = true
tokio.workspace = true
anyhow.workspace = true
tower-http.workspace = true