[package]
name = "bin"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "homelink"
path = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib = { path = "../core" }
hap-metadata = { path = "../target-platform/hap/hap-metadata" }
target-hap = { path = "../target-platform/hap/target-hap" }
xiaomi-integration= { path = "../source-platform/xiaomi/xiaomi-integration" }
hl-integration = { path = "../hl-integration" }


axum.workspace = true
log4rs.workspace = true
log.workspace = true
tokio.workspace = true
anyhow.workspace = true
tower-http.workspace = true
