[target.x86_64-unknown-linux-musl]
#pre-build = ["apt-get update && apt-get install -y libdbus-1-dev"]
image = "homelink-context-x86_64-unknown-linux-musl:v1"
# context = "./docker"
# dockerfile = "./docker/Dockerfile.x86_64-unknown-linux-musl"
