//! `SeaORM` Entity. Generated by sea-orm-hap_platform-metadata 0.11.3

use std::collections::HashMap;
use sea_orm::ActiveValue::Set;
use sea_orm::entity::prelude::*;
use sea_orm::FromJsonQueryResult;
use serde::{Deserialize, Serialize};
use hap::accessory::AccessoryCategory;
use hap::BonjourStatusFlag;
use hap::pairing::Pairing;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

#[derive(EnumIter, DeriveActiveEnum, Copy, Clone, Hash, Debug, PartialEq, Eq, Serialize, Deserialize, )]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum BridgeCategory {
    Other = 1,
    Bridge = 2,
    Fan = 3,
    GarageDoorOpener = 4,
    Lightbulb = 5,
    DoorLock = 6,
    Outlet = 7,
    Switch = 8,
    Thermostat = 9,
    Sensor = 10,
    SecuritySystem = 11,
    Door = 12,
    Window = 13,
    WindowCovering = 14,
    ProgrammableSwitch = 15,
    RangeExtender = 16,
    IpCamera = 17,
    VideoDoorbell = 18,
    AirPurifier = 19,
    AirHeater = 20,
    AirConditioner = 21,
    AirHumidifier = 22,
    AirDehumidifier = 23,
    AppleTv = 24,
    Speaker = 26,
    Airport = 27,
    Sprinkler = 28,
    Faucet = 29,
    ShowerHead = 30,
    Television = 31,
    TargetController = 32,
    WiFiRouter = 33,
    AudioReceiver = 34,
    TelevisionSetTopBox = 35,
    TelevisionStreamingStick = 36,
}

impl Into<AccessoryCategory> for BridgeCategory {
    fn into(self) -> AccessoryCategory {
        let value = self.into_value().clone();
        AccessoryCategory::from(value as u8)
    }
}

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "hap_bridge"
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize, FromJsonQueryResult)]
pub struct BonjourStatusFlagWrapper(pub BonjourStatusFlag);

#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize, FromJsonQueryResult, Default)]
pub struct PairingsWrapper(pub HashMap<uuid::Uuid, Pairing>);


#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize, FromJsonQueryResult)]
pub struct BridgeInfo {
    pub serial_number: String,
    pub model: String,
    pub manufacturer: String,
    pub software_revision: Option<String>,
}


#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub bridge_id: i64,
    pub pin_code: i64,
    pub port: i64,
    pub category: BridgeCategory,
    pub name: String,
    pub mac: String,
    pub setup_id: String,
    pub host: Option<String>,
    pub disabled: bool,
    ///是否是单配件桥接器
    pub single_accessory: bool,
    ///配对列表
    pub pairings: PairingsWrapper,
    pub device_ed25519_keypair: String,
    pub configuration_number: i64,
    pub status_flag: BonjourStatusFlagWrapper,
    pub max_peers: Option<i64>,
    pub info: BridgeInfo,
    pub create_at: chrono::NaiveDateTime,
    pub update_at: chrono::NaiveDateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    BridgeId,
    Name,
    PinCode,
    Port,
    Category,
    Mac,
    SetupId,
    Disabled,
    SingleAccessory,
    Pairings,
    Host,
    DeviceEd25519Keypair,
    ConfigurationNumber,
    StatusFlag,
    MaxPeers,
    Info,
    CreateAt,
    UpdateAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    BridgeId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::hap_accessory::Entity")]
    HapAccessory,
}

// `Related` trait has to be implemented by hand
impl Related<super::hap_accessory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HapAccessory.def()
    }
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::BridgeId => ColumnType::BigInteger.def(),
            Self::Name => ColumnType::String(None).def(),
            Self::Mac => ColumnType::String(None).def(),
            Self::SetupId => ColumnType::String(None).def(),
            Self::Disabled => ColumnType::Boolean.def(),
            Self::PinCode => ColumnType::BigInteger.def().unique(),
            Self::Category => ColumnType::Integer.def(),
            Self::Port => ColumnType::Integer.def(),
            Self::SingleAccessory => ColumnType::Boolean.def(),
            Self::Pairings => ColumnType::String(None).def().null(),
            Self::Host => ColumnType::String(Some(64)).def().null(),
            Self::DeviceEd25519Keypair => ColumnType::String(Some(255)).def(),
            Self::ConfigurationNumber => ColumnType::BigInteger.def(),
            Self::StatusFlag => ColumnType::Integer.def(),
            Self::MaxPeers => ColumnType::BigInteger.def().null(),
            Self::Info => ColumnType::String(None).def(),
            Self::CreateAt => ColumnType::DateTime.def(),
            Self::UpdateAt => ColumnType::DateTime.def(),
        }
    }
}


impl ActiveModelBehavior for ActiveModel {
    fn new() -> Self {
        Self {
            create_at: Set(chrono::Local::now().naive_local()),
            update_at: Set(chrono::Local::now().naive_local()),
            ..<Self as ActiveModelTrait>::default()
        }
    }
}
