# Built from https://github.com/qwandor/cross/blob/context/docker/Dockerfile.x86_64-unknown-linux-musl
FROM ubuntu:22.04

COPY common.sh lib.sh /
RUN /common.sh

COPY  cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

COPY musl.sh /
RUN /musl.sh TARGET=x86_64-linux-musl

RUN apt-get update && \
	apt-get install -y libdbus-1-dev pkg-config

ENV CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=x86_64-linux-musl-gcc \
    CC_x86_64_unknown_linux_musl=x86_64-linux-musl-gcc \
    CXX_x86_64_unknown_linux_musl=x86_64-linux-musl-g++
