# https://home.miot-spec.com/s/miaomiaoce.sensor_ht.t1
id = "miaomiaoce.sensor_ht.t1"
version = "1.0.0"
model = "miaomiaoce.sensor_ht.t1"
model_name = "小米米家电子温湿度计Pro"
fw_version = "2.1.8_0044"
model_icon = ""
[[devices]]
# 设备接入方式
integration = "xiaomi_gw_ble"
desc = "温湿度计"
[devices.params]
[[devices.accessories]]
#插座类型
category = "Sensor"
hap_delegate.model = "common.ble_value_mapping"
#hap_delegate.params = [{ ctag = "PowerState", siid = 2, piid = 1 }]
# 配件下的服务
[[devices.accessories.services]]
service_type = "TemperatureSensor"
chars = [
    { memo = "当前温度", char_type = "CurrentTemperature", info = { min_value = -30, max_value = 100 } }
]
tag = "temperature"
[[devices.accessories.services]]
service_type = "HumiditySensor"
tag = "humidity"
chars = [
    { memo = "当前湿度", char_type = "CurrentRelativeHumidity", info = { min_value = 0, max_value = 100 } }
]